# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: root_store.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10root_store.proto\x12\x11\x63hrome_root_store\"{\n\rConstraintSet\x12\x1e\n\x11sct_not_after_sec\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x1e\n\x11sct_all_after_sec\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x14\n\x12_sct_not_after_secB\x14\n\x12_sct_all_after_sec\"\x90\x01\n\x0bTrustAnchor\x12\r\n\x03\x64\x65r\x18\x01 \x01(\x0cH\x00\x12\x14\n\nsha256_hex\x18\x02 \x01(\tH\x00\x12\x16\n\x0e\x65v_policy_oids\x18\x03 \x03(\t\x12\x35\n\x0b\x63onstraints\x18\x04 \x03(\x0b\x32 .chrome_root_store.ConstraintSetB\r\n\x0b\x63\x65rtificate\"Y\n\tRootStore\x12\x35\n\rtrust_anchors\x18\x01 \x03(\x0b\x32\x1e.chrome_root_store.TrustAnchor\x12\x15\n\rversion_major\x18\x02 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'root_store_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSTRAINTSET._serialized_start=39
  _CONSTRAINTSET._serialized_end=162
  _TRUSTANCHOR._serialized_start=165
  _TRUSTANCHOR._serialized_end=309
  _ROOTSTORE._serialized_start=311
  _ROOTSTORE._serialized_end=400
# @@protoc_insertion_point(module_scope)
